In [191]:
import pandas as pd

In [192]:
df = pd.read_csv('C:/Users/Dell/Downloads/dirtystpredata/retail_store_sales.csv')

In [193]:
df.shape

(12575, 11)

In [194]:
df.columns

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='object')

In [195]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [196]:
df.describe(include='all')

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
count,12575,12575,12575,11362,11966.000000,11971.000000,11971.000000,12575,12575,12575,8376
unique,12575,25,8,200,NaN,NaN,NaN,3,2,1114,2
top,TXN_2407494,CUST_05,Electric household essentials,Item_2_BEV,NaN,NaN,NaN,Cash,Online,2022-05-30,True
freq,1,544,1591,126,NaN,NaN,NaN,4310,6354,26,4219
mean,NaN,NaN,NaN,NaN,23.365912,5.536380,129.652577,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,10.743519,2.857883,94.750697,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,5.000000,1.000000,5.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,14.000000,3.000000,51.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,23.000000,6.000000,108.500000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,33.500000,8.000000,192.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,41.000000,10.000000,410.000000,NaN,NaN,NaN,NaN

In [197]:
df.head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
8,TXN_9728486,CUST_23,Furniture,Item_16_FUR,27.5,1.0,27.5,Credit Card,In-store,2023-04-26,False
9,TXN_2722661,CUST_25,Butchers,Item_22_BUT,36.5,3.0,109.5,Cash,Online,2024-03-14,False

In [198]:
#removing extra spaces
df.columns = df.columns.str.strip()

In [199]:
df.columns

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='object')

In [200]:
#removing space and adding "_" for making things easier in future

df.columns = [c.replace(' ', '_') for c in df.columns]

In [201]:
df.columns

Index(['Transaction_ID', 'Customer_ID', 'Category', 'Item', 'Price_Per_Unit',
       'Quantity', 'Total_Spent', 'Payment_Method', 'Location',
       'Transaction_Date', 'Discount_Applied'],
      dtype='object')

In [202]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    12575 non-null  object
 1   Customer_ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price_Per_Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total_Spent       11971 non-null  float64
 7   Payment_Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction_Date  12575 non-null  object
 10  Discount_Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [203]:
# now fixing Data type of Transaction_Date
df['Transaction_Date']  = pd.to_datetime(df['Transaction_Date'], errors = 'coerce')

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    12575 non-null  object
 1   Customer_ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price_Per_Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total_Spent       11971 non-null  float64
 7   Payment_Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction_Date  12575 non-null  datetime64[ns]
 10  Discount_Applied  8376 non-null   object
dtypes: datetime64[ns](1), float64(3), object(7)
memory usage: 1.1+ MB

In [205]:
# Now Fixing The Numeric Columns

numeric_cols = ['Price_Per_Unit', 'Quantity', 'Total_Spent']
for col in numeric_cols:
    if df[col].dtype == 'object':
        df[col] = df[col].str.replace('[$,]', '', regex = True)
    df[col] = pd.to_numeric(df[col], errors = 'coerce')

In [206]:
df.head()

,Transaction_ID,Customer_ID,Category,Item,Price_Per_Unit,Quantity,Total_Spent,Payment_Method,Location,Transaction_Date,Discount_Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [207]:
df.isnull().sum()

Transaction_ID         0
Customer_ID            0
Category               0
Item                1213
Price_Per_Unit       609
Quantity             604
Total_Spent          604
Payment_Method         0
Location               0
Transaction_Date       0
Discount_Applied    4199
dtype: int64

In [208]:
df.duplicated().sum()

np.int64(0)

In [209]:
df['Transaction_ID'].duplicated().sum()

np.int64(0)

In [210]:
#double checking how many unique customers again
unique_cust = df['Customer_ID'].nunique()
print(f"I have {unique_cust} unique customers.")

I have 25 unique customers.

In [211]:
df.head()

,Transaction_ID,Customer_ID,Category,Item,Price_Per_Unit,Quantity,Total_Spent,Payment_Method,Location,Transaction_Date,Discount_Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [212]:
df['Category'].isnull().sum()

np.int64(0)

In [213]:
df['Category'].unique()

array(['Patisserie', 'Milk Products', 'Butchers', 'Beverages', 'Food',
       'Furniture', 'Electric household essentials',
       'Computers and electric accessories'], dtype=object)

In [214]:
#This will show me list of every category and exactly how many transactions happened for each.
df['Category'].value_counts()

Category
Electric household essentials         1591
Furniture                             1591
Food                                  1588
Milk Products                         1584
Butchers                              1568
Beverages                             1567
Computers and electric accessories    1558
Patisserie                            1528
Name: count, dtype: int64

In [218]:
# checking null values in Item Column
df['Item'].isnull().sum()

np.int64(1213)

In [219]:
#Checking which category has the most missing "Item" values
df[df['Item'].isnull()]['Category'].value_counts()

Category
Food                                  162
Computers and electric accessories    161
Patisserie                            159
Milk Products                         159
Electric household essentials         154
Butchers                              147
Beverages                             140
Furniture                             131
Name: count, dtype: int64

In [233]:
#Can't delete those null item values because the next necessary columns are not checked yet so will name all nul items 
#as Unknown Item
df['Item'] = df['Item'].fillna('Unknown_Item')

In [234]:
df['Item'].isnull().sum()

np.int64(0)

In [235]:
df[df['Item'].isnull()]['Category'].value_counts()

Series([], Name: count, dtype: int64)

In [244]:
# 1. Identify rows where BOTH Quantity and Total_Spent are missing
# We use .dropna with the 'subset' and 'how' parameters
df_cleaned = df.dropna(subset = ['Quantity', 'Total_Spent'], how = 'all')

In [245]:
# now will see how many rows we actually removed
rows_removed = len(df) - len(df_cleaned)
print(f"Cleaned! We removed {rows_removed} rows that had no Quantity And Total_Spent.")

Cleaned! We removed 0 rows that had no Quantity And Total_Spent.

In [246]:
# Check if there are rows where money is 0 but quantity exists
zero_sales = df[(df['Total_Spent'] == 0) & (df['Quantity'] > 0)]
print(f"Transactions with 0 cost but > 0 quantity: {len(zero_sales)}")

Transactions with 0 cost but > 0 quantity: 0

In [253]:
df['Price_Per_Unit'].isnull().sum()

np.int64(609)

In [255]:
# Check if any of those 609 rows have a Quantity of 0 or NaN
check_zeros = df[df['Price_Per_Unit'].isnull()]['Quantity'].value_counts(dropna=False)
print("Quantity values for the missing price rows:")
print(check_zeros)

Quantity values for the missing price rows:
Quantity
2.0     77
9.0     74
8.0     71
7.0     63
5.0     57
4.0     56
10.0    55
1.0     55
3.0     54
6.0     47
Name: count, dtype: int64

In [257]:
#Recovering missing prices from Total and Quantity
df.loc[:, 'Price_Per_Unit'] = df['Price_Per_Unit'].fillna(df['Total_Spent'] / df['Quantity'])

In [260]:
#now it will give 0 null values
df['Price_Per_Unit'].isnull().sum()

np.int64(0)

In [261]:
print(f"Missing Quantities: {df['Quantity'].isnull().sum()}")

Missing Quantities: 0

In [264]:
print(f"Missing Total: {df['Total_Spent'].isnull().sum()}")

Missing Total: 0

In [268]:
df['Discount_Applied'].isnull().sum()

np.int64(3988)

In [294]:
#Creating the 'Calculated' price
calculated_total = df['Price_Per_Unit'] * df['Quantity']

In [298]:
# Check if there is ANY row where the calculation is different from the actual Total_Spent
mismatches = (df['Total_Spent'] - calculated_total).abs() > 0.01

In [299]:
# Count how many rows failed the test
mismatch_count = mismatches.sum()

In [300]:
print(f"Number of rows where Price * Quantity != Total: {mismatch_count}")

Number of rows where Price * Quantity != Total: 0

In [314]:
# If the count is 0, then we have PROOF to set everything to False
if mismatch_count == 0:
    df['Discount_Applied'] = False

In [319]:
df['Item'] = df['Item'].replace('Unknown Item', 'Unknown_Item')

In [ ]:
print(df.dtypes)

In [321]:
#now we can see those empty items are unknown items
#and will remove Discount Applied column as there are no DIscounts given
df.describe(include='all')

,Transaction_ID,Customer_ID,Category,Item,Price_Per_Unit,Quantity,Total_Spent,Payment_Method,Location,Transaction_Date,Discount_Applied
count,11971,11971,11971,11971,11971.000000,11971.000000,11971.000000,11971,11971,11971,11971
unique,11971,25,8,201,NaN,NaN,NaN,3,2,NaN,1
top,TXN_2407494,CUST_24,Furniture,Unknown_Item,NaN,NaN,NaN,Cash,Online,NaN,False
freq,1,519,1525,609,NaN,NaN,NaN,4103,6068,NaN,11971
mean,NaN,NaN,NaN,NaN,23.360872,5.536380,129.652577,NaN,NaN,2023-07-13 02:26:23.627099136,NaN
min,NaN,NaN,NaN,NaN,5.000000,1.000000,5.000000,NaN,NaN,2022-01-01 00:00:00,NaN
25%,NaN,NaN,NaN,NaN,14.000000,3.000000,51.000000,NaN,NaN,2022-09-29 00:00:00,NaN
50%,NaN,NaN,NaN,NaN,23.000000,6.000000,108.500000,NaN,NaN,2023-07-13 00:00:00,NaN
75%,NaN,NaN,NaN,NaN,33.500000,8.000000,192.000000,NaN,NaN,2024-04-24 00:00:00,NaN
max,NaN,NaN,NaN,NaN,41.000000,10.000000,410.000000,NaN,NaN,2025-01-18 00:00:00,NaN
std,NaN,NaN,NaN,NaN,10.741889,2.857883,94.750697,NaN,NaN,NaN,NaN

In [335]:
#Convert Quantity to Integer (since there are no 0.5 quantities)
df['Quantity'] = df['Quantity'].astype(int)

In [ ]:
#To optimize the data for analysis and remove redundant features, I dropped this column.
df = df.drop(columns = ['Discount_Applied'])

In [336]:
df.head()

,Transaction_ID,Customer_ID,Category,Item,Price_Per_Unit,Quantity,Total_Spent,Payment_Method,Location,Transaction_Date
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10,185.0,Digital Wallet,Online,2024-04-08
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9,261.0,Digital Wallet,Online,2023-07-23
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2,43.0,Credit Card,Online,2022-10-05
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9,247.5,Credit Card,Online,2022-05-07
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7,87.5,Digital Wallet,Online,2022-10-02

In [330]:
# Export to CSV
df.to_csv('Cleaned_Retail_Data.csv', index=False)

In [337]:
folder_path = r'C:/Users/Dell/Desktop\pythonDS/pythonfordsagain/Retail_Data_cleaning_n_analysis'
file_name = 'Cleaned_Retail_Analysis_v1.csv'

In [338]:
df.to_csv(f"{folder_path}\\{file_name}", index=False)

In [339]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11971 entries, 0 to 12574
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    11971 non-null  object
 1   Customer_ID       11971 non-null  object
 2   Category          11971 non-null  object
 3   Item              11971 non-null  object
 4   Price_Per_Unit    11971 non-null  float64
 5   Quantity          11971 non-null  int64
 6   Total_Spent       11971 non-null  float64
 7   Payment_Method    11971 non-null  object
 8   Location          11971 non-null  object
 9   Transaction_Date  11971 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 1.3+ MB